---
title: "My first blog post"
date: 2021-03-02
---
author: HowlingCargo
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A site where I attempt to make something of my life using the wonderful technology of GitHib
  (I hold no legal responsibility for any personal issues with GitHub and it's supposed state of being "wonderful".
  I have no professional affiliation with GitHub, and as such would have absolutely have no reason to inflate its status as "wonderful".
  Any insinuation otherwise will be met with fervent "Nuh-uhs" and possibly even "I have no idea what you're talking about".)

# social links
twitter_username: None_that_I_actively_use # DO NOT include the @ character, or else the build will fail!
github_username:  HowlingCargo # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
